# Generated by Django 5.2.17 on 2026-08-20 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor_label', models.CharField(blank=True, help_text='Username captured at write time, so the trail survives user deletion.', max_length=150)),
                ('action', models.CharField(choices=[('UPLOAD_PRESIGN', 'Upload presigned'), ('UPLOAD_COMMIT', 'Upload committed'), ('UPLOAD_ABORT', 'Upload aborted'), ('ITEM_UPDATE', 'Item updated'), ('ITEM_ARCHIVE', 'Item archived'), ('ITEM_PURGE', 'Item purged'), ('ORPHAN_REAP', 'Orphan reaped'), ('COUNTS_RECONCILE', 'Counts reconciled')], db_index=True, max_length=32)),
                ('object_type', models.CharField(blank=True, max_length=64)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['action', '-created_at'], name='audit_action_created_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_object_idx')],
            },
        ),
    ]
