# Generated by Django 5.2.17 on 2026-08-20 07:10

import apps.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppClient',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('key_prefix', models.CharField(db_index=True, max_length=12, unique=True)),
                ('key_hash', models.CharField(editable=False, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit_per_min', models.PositiveIntegerField(default=120)),
                ('last_used_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('allowed_features', models.ManyToManyField(blank=True, help_text='Types this key may read. Leave empty to allow all.', related_name='app_clients', to='catalog.feature')),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['key_prefix', 'is_active'], name='appclient_prefix_act_idx')],
            },
        ),
    ]
