# Generated by Django 5.2.17 on 2026-08-20 07:10

import apps.core.ids
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9]+(?:-[a-z0-9]+)*$', 'Use lowercase letters, digits and single hyphens only.')])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9]+(?:-[a-z0-9]+)*$', 'Use lowercase letters, digits and single hyphens only.')])),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('allowed_mimes', models.JSONField(default=list, help_text='Whitelist of accepted Content-Type values for this type.')),
                ('max_file_bytes', models.BigIntegerField(default=26214400, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_pixels', models.BigIntegerField(default=50000000, help_text='Decompression-bomb ceiling: width * height must not exceed this.', validators=[django.core.validators.MinValueValidator(1)])),
                ('strict_zip_structure', models.BooleanField(default=False, help_text='Reject zip uploads that lack a conf/ entry (Shimeji packs).')),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('priority', 'name'),
                'indexes': [models.Index(fields=['is_active', 'priority'], name='feature_active_prio_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, validators=[django.core.validators.RegexValidator('^[a-z0-9]+(?:-[a-z0-9]+)*$', 'Use lowercase letters, digits and single hyphens only.')])),
                ('description', models.TextField(blank=True)),
                ('thumbnail_key', models.CharField(blank=True, max_length=512)),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('has_subcategories', models.BooleanField(default=False, editable=False)),
                ('item_count', models.PositiveIntegerField(default=0, editable=False)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='catalog.feature')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('priority', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, validators=[django.core.validators.RegexValidator('^[a-z0-9]+(?:-[a-z0-9]+)*$', 'Use lowercase letters, digits and single hyphens only.')])),
                ('description', models.TextField(blank=True)),
                ('thumbnail_key', models.CharField(blank=True, max_length=512)),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('item_count', models.PositiveIntegerField(default=0, editable=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'subcategories',
                'ordering': ('priority', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('premium', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0, help_text='Lower sorts first.')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Static image'), ('GIF', 'Animated GIF'), ('VIDEO', 'Video'), ('ZIP', 'Zip archive (Shimeji pack)')], db_index=True, max_length=8)),
                ('is_live', models.BooleanField(default=False, help_text='Live wallpaper / animated battery asset.')),
                ('file_key', models.CharField(max_length=512, unique=True)),
                ('file_bytes', models.BigIntegerField(default=0)),
                ('file_mime', models.CharField(blank=True, max_length=100)),
                ('file_etag', models.CharField(blank=True, db_index=True, max_length=128)),
                ('preview_key', models.CharField(blank=True, max_length=512)),
                ('preview_bytes', models.BigIntegerField(default=0)),
                ('preview_mime', models.CharField(blank=True, max_length=100)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('orientation', models.CharField(blank=True, choices=[('PORTRAIT', 'Portrait'), ('LANDSCAPE', 'Landscape'), ('SQUARE', 'Square')], db_index=True, max_length=10)),
                ('resolution', models.CharField(blank=True, choices=[('SD', 'SD'), ('HD', 'HD (720p)'), ('FHD', 'Full HD (1080p)'), ('QHD', 'Quad HD (1440p)'), ('UHD_4K', '4K UHD')], db_index=True, max_length=8)),
                ('dominant_color', models.CharField(blank=True, help_text='Hex like #1a2b3c, for image placeholders.', max_length=7)),
                ('zip_entries', models.PositiveIntegerField(blank=True, null=True)),
                ('zip_has_conf', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('ARCHIVED', 'Archived')], default='PENDING', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.category')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.feature')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.subcategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='items', to='catalog.tag')),
            ],
            options={
                'ordering': ('priority', '-created_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['feature', 'is_active', 'priority'], name='category_feat_act_prio_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('feature', 'slug'), name='category_unique_feature_slug'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['category', 'is_active', 'priority'], name='subcat_cat_act_prio_idx'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('category', 'slug'), name='subcategory_unique_cat_slug'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('id', 'category'), name='subcategory_id_category_uniq'),
        ),
        migrations.AddIndex(
            model_name='mediaitem',
            index=models.Index(condition=models.Q(('is_active', True), ('status', 'READY')), fields=['priority', '-created_at', '-id'], name='item_pub_feed_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaitem',
            index=models.Index(condition=models.Q(('is_active', True), ('status', 'READY')), fields=['feature', 'priority', '-created_at', '-id'], name='item_pub_feature_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaitem',
            index=models.Index(condition=models.Q(('is_active', True), ('status', 'READY')), fields=['category', 'priority', '-created_at', '-id'], name='item_pub_category_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaitem',
            index=models.Index(condition=models.Q(('is_active', True), ('status', 'READY')), fields=['subcategory', 'priority', '-created_at', '-id'], name='item_pub_subcat_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaitem',
            index=models.Index(condition=models.Q(('is_active', True), ('status', 'READY')), fields=['feature', 'media_type', 'priority', '-created_at', '-id'], name='item_pub_feat_mtype_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaitem',
            index=models.Index(condition=models.Q(('is_active', True), ('status', 'READY')), fields=['feature', 'is_live', 'priority', '-created_at', '-id'], name='item_pub_feat_live_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaitem',
            index=models.Index(fields=['-updated_at'], name='item_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaitem',
            index=models.Index(fields=['file_etag', 'file_bytes'], name='item_etag_bytes_idx'),
        ),
        migrations.AddConstraint(
            model_name='mediaitem',
            constraint=models.CheckConstraint(condition=models.Q(('file_bytes__gte', 0), ('preview_bytes__gte', 0)), name='item_sizes_non_negative'),
        ),
    ]
