# Generated by Django 5.2.17 on 2026-08-20 07:10

import apps.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadTicket',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_key', models.CharField(max_length=512, unique=True)),
                ('kind', models.CharField(choices=[('ASSET', 'Main asset'), ('PREVIEW', 'Preview image')], default='ASSET', max_length=8)),
                ('declared_name', models.CharField(blank=True, max_length=255)),
                ('declared_mime', models.CharField(max_length=100)),
                ('declared_bytes', models.BigIntegerField()),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('COMMITTED', 'Committed'), ('ABORTED', 'Aborted'), ('EXPIRED', 'Expired')], default='ISSUED', max_length=10)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='catalog.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upload_tickets', to=settings.AUTH_USER_MODEL)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='catalog.feature')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='catalog.subcategory')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'expires_at'], name='ticket_status_exp_idx'), models.Index(fields=['created_by', '-created_at'], name='ticket_creator_idx')],
            },
        ),
    ]
